//
//  SDevFlatColors.swift
//  SDevFlatColors
//
//  Created by Sedat Ciftci on 19/05/15.
//  Copyright (c) 2015 Sedat Ciftci. All rights reserved.
//

import UIKit

public extension UInt {
    func convertToUIColor() -> UIColor {
        return UIColor(
            red: CGFloat((self & 0xFF0000) >> 16) / 255.0,
            green: CGFloat((self & 0x00FF00) >> 8) / 255.0,
            blue: CGFloat(self & 0x0000FF) / 255.0,
            alpha: CGFloat(1.0)
        )
    }
}

public enum FlatColors {
    case turquoise,
    emerald,
    peterRiver,
    amethyst,
    wetAsphalty,
    greenSea,
    nephritis,
    belizeHole,
    wisteria,
    midnightBlue,
    sunFlower,
    carrot,
    alizarin,
    clouds,
    concrete,
    orange,
    pumpkin,
    pomegranate,
    silver,
    asbestos,
    chestnuteRose,
    thunderbird,
    oldBrick,
    flamingo,
    valencia,
    tallPoppy,
    monza,
    cinnabar,
    razzmatazz,
    sunsetOrange,
    waxFlower,
    cabaret,
    newYorkPink,
    radicalRed,
    sunglo,
    snuff,
    rebeccapurple,
    honeyFlower,
    wistful,
    plum,
    seance,
    mediumPurple,
    lightWisteria,
    studio,
    sanMarino,
    aliceBlue,
    royalBlue,
    pictonBlue,
    spray,
    shakespeare,
    hummingBird,
    curious,
    madison,
    dodgerBlue,
    ming,
    ebonyClay,
    malibu,
    summerySky,
    chambray,
    pickledBluewood,
    hoki,
    jellyBean,
    jacksonsPurple,
    jordyBlue,
    steelBlue,
    fountainBlue,
    mediumTurquoise,
    aquaIsland,
    gossip,
    darkSeaGreen,
    eucalyptus,
    caribbeanGreen,
    silverTree,
    downy,
    mountainMeadow,
    lightSeaGreen,
    mediumAquamarine,
    madang,
    riptide,
    shamrock,
    niagara,
    greenHaze,
    oceanGreen,
    niagaraOne,
    jade,
    salem,
    observatory,
    jungleGreen,
    capeHoney,
    california,
    fireBush,
    tahitiGold,
    casablanca,
    crusta,
    seaBuckthorn,
    lightningYellow,
    burntOrange,
    butterCup,
    ecstasy,
    sandstorm,
    jaffa,
    zest,
    whiteSmoke,
    lynch,
    pumice,
    gallery,
    silverSand,
    porcelain,
    cascade,
    iron,
    edward,
    cararra
}

var colors: Dictionary<FlatColors, UInt> = [
    FlatColors.turquoise: UInt(0x1abc9c),
    FlatColors.emerald: UInt(0x2ecc71),
    FlatColors.peterRiver: UInt(0x3498db),
    FlatColors.amethyst: UInt(0x9b59b6),
    FlatColors.wetAsphalty: UInt(0x34495e),
    FlatColors.greenSea: UInt(0x16a085),
    FlatColors.nephritis: UInt(0x27ae60),
    FlatColors.belizeHole: UInt(0x2980b9),
    FlatColors.wisteria: UInt(0x8e44ad),
    FlatColors.midnightBlue: UInt(0x2c3e50),
    FlatColors.sunFlower: UInt(0xf1c40f),
    FlatColors.carrot: UInt(0xe67e22),
    FlatColors.alizarin: UInt(0xe74c3c),
    FlatColors.clouds: UInt(0xecf0f1),
    FlatColors.concrete: UInt(0x95a5a6),
    FlatColors.orange: UInt(0xf39c12),
    FlatColors.pumpkin: UInt(0xd35400),
    FlatColors.pomegranate: UInt(0xc0392b),
    FlatColors.silver: UInt(0xbdc3c7),
    FlatColors.asbestos: UInt(0x7f8c8d),
    FlatColors.chestnuteRose: UInt(0xd24d57),
    FlatColors.thunderbird: UInt(0xD91E18),
    FlatColors.oldBrick: UInt(0x96281B),
    FlatColors.flamingo: UInt(0xEF4836),
    FlatColors.valencia: UInt(0xD64541),
    FlatColors.tallPoppy: UInt(0xC0392B),
    FlatColors.monza: UInt(0xCF000F),
    FlatColors.cinnabar: UInt(0xE74C3C),
    FlatColors.razzmatazz: UInt(0xDB0A5B),
    FlatColors.sunsetOrange: UInt(0xF64747),
    FlatColors.waxFlower: UInt(0xF1A9A0),
    FlatColors.cabaret: UInt(0xD2527F),
    FlatColors.newYorkPink: UInt(0xE08283),
    FlatColors.radicalRed: UInt(0xF62459),
    FlatColors.sunglo: UInt(0xE26A6A),
    FlatColors.snuff: UInt(0xDCC6E0),
    FlatColors.rebeccapurple: UInt(0x663399),
    FlatColors.honeyFlower: UInt(0x674172),
    FlatColors.wistful: UInt(0xAEA8D3),
    FlatColors.plum: UInt(0x913D88),
    FlatColors.seance: UInt(0x9A12B3),
    FlatColors.mediumPurple: UInt(0xBF55EC),
    FlatColors.lightWisteria: UInt(0xBE90D4),
    FlatColors.studio: UInt(0x8E44AD),
    FlatColors.sanMarino: UInt(0x446CB3),
    FlatColors.aliceBlue: UInt(0xE4F1FE),
    FlatColors.royalBlue: UInt(0x4183D7),
    FlatColors.pictonBlue: UInt(0x22A7F0),
    FlatColors.spray: UInt(0x81CFE0),
    FlatColors.shakespeare: UInt(0x52B3D9),
    FlatColors.hummingBird: UInt(0xC5EFF7),
    FlatColors.curious: UInt(0x3498DB),
    FlatColors.madison: UInt(0x2C3E50),
    FlatColors.dodgerBlue: UInt(0x19B5FE),
    FlatColors.ming: UInt(0x336E7B),
    FlatColors.ebonyClay: UInt(0x22313F),
    FlatColors.malibu: UInt(0x6BB9F0),
    FlatColors.summerySky: UInt(0x1E8BC3),
    FlatColors.chambray: UInt(0x3A539B),
    FlatColors.pickledBluewood: UInt(0x34495E),
    FlatColors.hoki: UInt(0x67809F),
    FlatColors.jellyBean: UInt(0x2574A9),
    FlatColors.jacksonsPurple: UInt(0x1F3A93),
    FlatColors.jordyBlue: UInt(0x89C4F4),
    FlatColors.steelBlue: UInt(0x4B77BE),
    FlatColors.fountainBlue: UInt(0x5C97BF),
    FlatColors.mediumTurquoise: UInt(0x4ECDC4),
    FlatColors.aquaIsland: UInt(0xA2DED0),
    FlatColors.gossip: UInt(0x87D37C),
    FlatColors.darkSeaGreen: UInt(0x90C695),
    FlatColors.eucalyptus: UInt(0x26A65B),
    FlatColors.caribbeanGreen: UInt(0x03C9A9),
    FlatColors.silverTree: UInt(0x68C3A3),
    FlatColors.downy: UInt(0x65C6BB),
    FlatColors.mountainMeadow: UInt(0x1BBC9B),
    FlatColors.lightSeaGreen: UInt(0x1BA39C),
    FlatColors.mediumAquamarine: UInt(0x66CC99),
    FlatColors.madang: UInt(0xC8F7C5),
    FlatColors.riptide: UInt(0x86E2D5),
    FlatColors.shamrock: UInt(0x2ECC71),
    FlatColors.niagara: UInt(0x16A085),
    FlatColors.greenHaze: UInt(0x019875),
    FlatColors.oceanGreen: UInt(0x4DAF7C),
    FlatColors.niagaraOne: UInt(0x2ABB9B),
    FlatColors.jade: UInt(0x00B16A),
    FlatColors.salem: UInt(0x1E824C),
    FlatColors.observatory: UInt(0x049372),
    FlatColors.jungleGreen: UInt(0x26C281),
    FlatColors.capeHoney: UInt(0xFDE3A7),
    FlatColors.california: UInt(0xF89406),
    FlatColors.fireBush: UInt(0xEB9532),
    FlatColors.tahitiGold: UInt(0xE87E04),
    FlatColors.casablanca: UInt(0xF4B350),
    FlatColors.crusta: UInt(0xF2784B),
    FlatColors.seaBuckthorn: UInt(0xEB974E),
    FlatColors.lightningYellow: UInt(0xF5AB35),
    FlatColors.burntOrange: UInt(0xD35400),
    FlatColors.butterCup: UInt(0xF39C12),
    FlatColors.ecstasy: UInt(0xF9690E),
    FlatColors.sandstorm: UInt(0xF9BF3B),
    FlatColors.jaffa: UInt(0xF27935),
    FlatColors.zest: UInt(0xE67E22),
    FlatColors.whiteSmoke: UInt(0xECECEC),
    FlatColors.lynch: UInt(0x6C7A89),
    FlatColors.pumice: UInt(0xD2D7D3),
    FlatColors.gallery: UInt(0xEEEEEE),
    FlatColors.silverSand: UInt(0xBDC3C7),
    FlatColors.porcelain: UInt(0xECF0F1),
    FlatColors.cascade: UInt(0x95A5A6),
    FlatColors.iron: UInt(0xDADFE1),
    FlatColors.edward: UInt(0xABB7B7),
    FlatColors.cararra: UInt(0xF2F1EF)
];

public extension UIColor {
    class func flat(_ color: FlatColors) -> UIColor {
        let selected: UInt = UInt(colors[color]!)
        return selected.convertToUIColor()
    }
}
